import type { FinanceState } from '@/lib/types';

export const DEFAULT_STATE: FinanceState = {
  settings: {
    mode: 'couple',
    primaryUserName: 'Alex',
    secondaryUserName: 'Sam',
    primaryIncome: 3200,
    secondaryIncome: 2800,
    primaryInvestmentPct: 12,
    secondaryInvestmentPct: 15,
    primaryInvestmentType: 'percentage',
    secondaryInvestmentType: 'percentage',
    primaryInvestmentFixed: 0,
    secondaryInvestmentFixed: 0,
    language: 'es',
    currency: 'USD',
  },
  categories: [
    { id: 'cat-uber', name: 'UBER', color: '#000000' },
    { id: 'cat-costco', name: 'Costco', color: '#E31837' },
    { id: 'cat-walmart', name: 'Walmart', color: '#0071CE' },
    { id: 'cat-nofrills', name: 'Nofrills', color: '#FFFF00' },
    { id: 'cat-rest', name: 'Restaurantes', color: '#FF5722' },
    { id: 'cat-rent', name: 'Renta -Hogar', color: '#3F51B5' },
    { id: 'cat-hydro', name: 'Toronto Hydro -Electricidad', color: '#FFEB3B' },
    { id: 'cat-amazon', name: 'Amazon', color: '#FF9900' },
  ],
  categoryGroups: [
    { id: 'group-gen', name: 'General', color: '#607D8B', budgetLimit: 0 },
    { id: 'group-merc', name: 'Mercado', color: '#4CAF50', budgetLimit: 500 },
  ],
  expenses: [
    {
      id: 'exp-1',
      owner: 'shared',
      categoryId: 'cat-rent',
      amount: 1850,
      date: '2026-03-01',
      note: 'Monthly Rent',
    },
    {
      id: 'exp-2',
      owner: 'user1',
      categoryId: 'cat-uber',
      amount: 24,
      date: '2026-03-05',
      note: 'Trip to office',
    },
    {
      id: 'exp-3',
      owner: 'shared',
      categoryId: 'cat-costco',
      amount: 156.40,
      date: '2026-03-10',
      note: 'Groceries',
    },
    {
      id: 'exp-4',
      owner: 'user2',
      categoryId: 'cat-amazon',
      amount: 45.99,
      date: '2026-03-12',
      note: 'Home decor',
    },
    {
      id: 'exp-5',
      owner: 'shared',
      categoryId: 'cat-hydro',
      amount: 85.20,
      date: '2026-03-15',
      note: 'Electricity bill',
    },
  ],
};
