import type { FinanceState } from '@/lib/types';

export const DEFAULT_STATE: FinanceState = {
  settings: {
    mode: 'couple',
    primaryUserName: 'Usuario 1',
    secondaryUserName: 'Usuario 2',
    primaryIncome: 5000,
    secondaryIncome: 4500,
    primaryInvestmentPct: 15,
    secondaryInvestmentPct: 15,
    primaryInvestmentType: 'percentage',
    secondaryInvestmentType: 'percentage',
    primaryInvestmentFixed: 0,
    secondaryInvestmentFixed: 0,
    language: 'es',
    currency: 'CAD',
  },
  categories: [
    { id: 'cat-uber', name: 'UBER', color: '#000000' },
    { id: 'cat-costco', name: 'Costco', color: '#E31837' },
    { id: 'cat-walmart', name: 'Walmart', color: '#0071CE' },
    { id: 'cat-nofrills', name: 'Nofrills', color: '#FFFF00' },
    { id: 'cat-rest', name: 'Restaurantes', color: '#FF5722' },
    { id: 'cat-rent', name: 'Renta -Hogar', color: '#3F51B5' },
    { id: 'cat-hydro', name: 'Toronto Hydro -Electricidad', color: '#FFEB3B' },
    { id: 'cat-amazon', name: 'Amazon', color: '#FF9900' },
  ],
  categoryGroups: [
    { id: '1', name: 'Renta', color: '#673AB7', budgetLimit: 3000 },
    { id: '2', name: 'Mercado', color: '#4CAF50', budgetLimit: 750 },
    { id: '3', name: 'Salidas', color: '#E91E63', budgetLimit: 600 },
    { id: '4', name: 'Servicios / Utilities', color: '#2196F3', budgetLimit: 450 },
    { id: '5', name: 'Transporte', color: '#00BCD4', budgetLimit: 400 },
    { id: '6', name: 'Gasolina', color: '#FF9800', budgetLimit: 150 },
    { id: '7', name: 'Extras', color: '#9C27B0', budgetLimit: 100 },
  ],
  expenses: [
    {
      id: 'exp-1',
      owner: 'shared',
      categoryId: 'cat-rent',
      amount: 1850,
      date: '2026-03-01',
      note: 'Monthly Rent',
    },
    {
      id: 'exp-2',
      owner: 'user1',
      categoryId: 'cat-uber',
      amount: 24,
      date: '2026-03-05',
      note: 'Trip to office',
    },
    {
      id: 'exp-3',
      owner: 'shared',
      categoryId: 'cat-costco',
      amount: 156.40,
      date: '2026-03-10',
      note: 'Groceries',
    },
    {
      id: 'exp-4',
      owner: 'user2',
      categoryId: 'cat-amazon',
      amount: 45.99,
      date: '2026-03-12',
      note: 'Home decor',
    },
    {
      id: 'exp-5',
      owner: 'shared',
      categoryId: 'cat-hydro',
      amount: 85.20,
      date: '2026-03-15',
      note: 'Electricity bill',
    },
  ],
};
